spring.application.name=Examen

spring.datasource.url=jdbc:mysql://localhost:3306/red_social?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mexico_City
spring.datasource.username=root
spring.datasource.password=emperador25_25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081